### ISSUE TITLE
ほめての動作条件緩和

### ISSUE THREAD

**Issue by isso0424** [potyama/GOOOOO#3]
「ほめて」って言ったときだけじゃなくて
「hogehogeほめて」とか「ほめてfugafuga」とかみたいな部分文字列で取れるようにすると使い勝手良さそう

**Comment by potyama** [comment]
@isso0424 チャン、今日もお仕事か、な、😃✋(^з<)💕（笑）😃☀ ❗本日のランチ🍴は、奮発しておにぎり🍙付き(^o^)(^з<)(^_^)😃✋😆😚😃😃☀ ❗誰だメタボなんて言ったやつハ(・_・;
対応しておくネ ❗

**Comment by potyama** [comment]
できたから閉じる
